### ISSUE TITLE
AppRouter is not a constructor

### ISSUE THREAD

**Issue by joergd** [marionettejs/marionette.approuter#4]
### Description

I am upgrading an existing app from Mn 3.5 to 4, and am using this extracted AppRouter (as opposed to the built-in Mn router)

In CoffeeScript, I now get the separate AppRouter like this:

    AppRouter = require 'marionette.approuter'

Then I try to instantiate it (like before)

    appRouter = new AppRouter({ ... })

But now I get the error:

    AppRouter is not a constructor

### Environment

1. Marionette version: 4.0.0
2. Backbone version: 1.3.3
3. Lodash: 4.17.10

Webpack: 3.5.5

**Comment by paulfalgout** [comment]
I don't see anything jumping out at me as to why this might be happening.  The UMD wrapper nearly matches `Marionette`'s so I'm surprised you'd have problems here and not with Mn.  Do you know which js file is being used with the coffeescript?  We're going to need more info to chase this down.  FWIW you may be able to use `Marionette.AppRouter`

**Comment by joergd** [comment]
The trace unfortunately doesn't give me much more than this:

    TypeError: AppRouter is not a constructor[Learn More] 
    App.prototype.setupRouter app.coffee:27
    App.prototype.onStart app.coffee:22
    triggerMethod$1 backbone.marionette.esm.js:356
    start backbone.marionette.esm.js:3185
    <anonymous> main.coffee:8
    <anonymous> http://127.0.0.1/assets/editor/main.bundle.self-bc08e27429bc73e48689d788b3b48c7fa156f02a5566f19f6c375832c485b701.js:962:1

This is literally a drop-in replacement - all I have changed is extending from the required marionette.approuter file, as opposed to the Marionette.AppRouter from v3.5.

Is there something I can do to get more helpful info?

**Comment by JSteunou** [comment]
Be careful you did not extend and used `constructor` with short syntax `constructor()` versus `constructor: function()`

**Comment by joergd** [comment]
Not sure what you mean - this is what I do (in a little more detail):

    MnRouter = require 'marionette.approuter'

    class MyRouter extends MnRouter({ appRoutes: ... })

    appRouter = new MyRouter({ controller: new AppController() })

This will give the error

    MyRouter.__super__ is undefined

I presume because MnRouter (from the marionette.approuter package) is not recognized as a constructor ...

**Comment by paulfalgout** [comment]
```js
MnRouter = require 'marionette.approuter'
console.log(MnRouter); // what's this?
```

**Comment by joergd** [comment]
{…}
    ​
    __esModule: true
    ​
    default: constructor()
    ​​
    __super__: Object { on: on(), listenTo: listenTo(), off: off(), … }
    ​​
    extend: function extend()
    ​​
    length: 1
    ​​
    name: "constructor"
    ​​
    prototype: Object { constructor: constructor(), appRoute: appRoute(), _processOnRoute: _processOnRoute(), … }
    ​​
    <prototype>: function ()
    ​
    <prototype>: Object { … }

**Comment by paulfalgout** [comment]
wait `extend` works?  so it looks to me like the export is ok..  hmm I'm kind of at a loss here.

If this was 
```
MnRouter = require 'marionette.approuter'
new MnRouter();
```
I could see the issue, but if this is off of the extend... I'm not sure what is going on.. all of that is from `Backbone.Router`

This is getting odder
How about `console.log(MyRouter)`?

**Comment by paulfalgout** [comment]
Is `class MyRouter extends MnRouter({ appRoutes: ... })` coffeescript?
This looks to be the problem to me..  looks like you're calling the constructor instead of extending it.
`class MyRouter extends MnRouter.extend({ appRoutes: ... })`

**Comment by joergd** [comment]
Sorry Paul - I contracted two lines incorrectly to make it more legible - the coffeescript I have is:

    class MyRouter extends MnRouter
     appRoutes:
      ...

Which should be totally fine.

**Comment by joergd** [comment]
MyRouter()
    ​
    __super__: undefined
    ​
    arguments: null
    ​
    caller: null
    ​
    default: function constructor()
    ​
    length: 0
    ​
    name: "MyRouter"
    ​
    prototype: Object { constructor: MyRouter(), appRoutes: {…}, initialize: initialize(), … }
    ​
    <prototype>: function ()

**Comment by JSteunou** [comment]
Try using marionette (backbone) `extend` function instead of `class extends` just to see if it makes a difference. Like I said, already had this issue because of `constructor()` in my code. Maybe your transpiler doing the same.

**Comment by joergd** [comment]
If I use the

    class MyRouter extends MnRouter.extend({ appRoutes: ... })

notation, I get the following error:

    parent is undefined

As to using backbone's extend notification, I have around 200 other classes defined using the extends notation - so the transpiler is doing it's work ok.

**Comment by paulfalgout** [comment]
In Backbone's `extend` `var parent = this;` So this is definitely an issue with `extends` somehow.  Is there any issue with using `MyRouter = MnRouter.extend({ appRoutes: ... })`?

**Comment by joergd** [comment]
Then I get the following ...

    MnRouter = require 'marionette.approuter'
    console.log MnRouter 
    MyRouter = MnRouter.extend({ appRoutes: ... })


    {…}
    ​
    __esModule: true
    ​
    default: function constructor()
    ​
    <prototype>: Object { … }
    appRouter.coffee:4
    14:23:10.790 [Show/hide message details.] TypeError: MnRouter.extend is not a function[Learn More] main.bundle.self-8028511db009ab45264c965ea47d5b32dde5b669ec2f47517331b8394fa16db2.js:11:13 

Weird.

**Comment by paulfalgout** [comment]
The `console.log` seemed to say otherwise previously? `extend: function extend()` https://github.com/marionettejs/marionette.approuter/issues/4#issuecomment-422814582
So does `MyRouter = Marionette.AppRouter.extend({ appRoutes: ... })` work?
Were there any other updates ie coffeescript or any bundler/babel like processor along with the Mn update? 
The code for approuter is pretty much identical to what it was before.
It is packaged differently, but as far as I can tell you're getting the results of the package correctly, so I do not think this is specifically an issue with `marionette.approuter` that wasn't there before.

**Comment by joergd** [comment]
Comment 4 was the output to `console.log MnRouter`

    MyRouter = Marionette.AppRouter.extend({ ... })

    error:
    Marionette.AppRouter is undefined

I only updated Marionette to 4.x, added AppRouter, and updated lodash 4.17.4 to 4.17.10.

Yeah really strange. I'll see if I can revert back to the older lodash, but kind of doubt that will make any difference.

**Comment by paulfalgout** [comment]
what changed between the console log [here](https://github.com/marionettejs/marionette.approuter/issues/4#issuecomment-422814582) and the one erroring?

**Comment by joergd** [comment]
The one erroring now has this

    Marionette = require 'backbone.marionette'
    MnRouter = require 'marionette.approuter'

And the #4 comment only has

    MnRouter = require 'marionette.approuter'

**Comment by paulfalgout** [comment]
you might check that your dependency tree only has one copy of Mn and Bb etc

**Comment by joergd** [comment]
I did an npm prune, which didn't make a difference. I also deleted the npm_modules folder - also no difference.

The only module that depends on marionette in my package file is marionette.approuter (which depends on the beta version), other than that no other dependencies.

**Comment by paulfalgout** [comment]
https://runkit.com/paulfalgout/test-approuter no errors here

**Comment by NicholasPeretti** [comment]
I solved in this way
``` javascript
const AppRouter = require('marionette.approuter').default
```
I had this kind of error before but I don't remember how I solve this.
I think it was something about ES6 modules.

**Comment by blikblum** [comment]
I've hit a similar error when extending MnObject

In my case the issue is that i was not transpiling the object method short notation.

The the following code crashes with "MyClass not a constructor"

```
var MyClass = MnObject.extend({
  constructor () {
     // init
  },
   
  myMethod () {
  }
})

var x = new MyClass()
```

Transpiling with babel to ie 11 compatible fixes it

Hopefully this can help
