### ISSUE TITLE
4.0.0-beta.1 of backbone.marionette as a dependency

### ISSUE THREAD

**Issue by danspam** [marionettejs/marionette.approuter#5]
In the package.json there is the following:

```
"dependencies": {
    "backbone.marionette": "^4.0.0, 4.0.0-beta.1"
  }
```
This is causing two version of backbone.marionette to be included when I Webpack my application. Does the inclusion of the beta version need to be there?

**Comment by graphographer** [comment]
I think it needs to be listed as a peerDependency.

**Comment by paulfalgout** [comment]
Good idea.  Sorry this took so long
